[versions]
kotlin = "2.3.0-Beta2"
kotlinx-serialization = "1.9.0"
quickMpp = "0.18"
equalsTester = "0.13"
karamelUtils = "0.1.1"
jmh = "1.37"
jmhPlugin = "0.7.3"
zeroJson = "0.1.1"

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
bitvector = { module = "io.github.adokky:bitvector", version = "0.9.2" }
equalsTester = { module = "io.github.adokky:equals-tester", version.ref = "equalsTester" }
karamelUtils-core = { module = "io.github.adokky:karamel-utils-core", version.ref = "karamelUtils" }
objectPool = { module = "io.github.adokky:object-pool", version = "1.0" }
zeroJson-core = { module = "io.github.adokky:zero-json-core", version.ref = "zeroJson" }
zeroJson-kotlinx = { module = "io.github.adokky:zero-json-kotlinx", version.ref = "zeroJson" }
jmh-processor = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }

[plugins]
jmh = { id = "me.champeau.jmh", version.ref = "jmhPlugin" }
quick-mpp = { id = "io.github.adokky.quick-mpp", version.ref = "quickMpp" }
quick-jvm = { id = "io.github.adokky.quick-jvm", version.ref = "quickMpp" }
quick-publish = { id = "io.github.adokky.quick-publish", version.ref = "quickMpp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }